### ISSUE TITLE
Add a contact page

### ISSUE THREAD

**Issue by alienlebarge** [alienlebarge/alienlebargech-v3#22]
### Description

There's nothing to contact me.

### Ask

Add a contact form.

### To Do

- [X] Check netlify doc #23 
- [X] Set up styles for form #23  
- [X] Build the form #23 
- [x] Test it
- [X] Add a confirmation page ff3c167506918d1571a792c0111cf7ff622b3289
- [x] Add a link in menu

### Additional Info

...
